services:
  mariadb_node1:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb_node1
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_GALERA_CLUSTER_NAME: my_galera_cluster
      MARIADB_GALERA_NODE_NAME: node1
      MARIADB_GALERA_NODE_ADDRESS: mariadb_node1
      MARIADB_GALERA_CLUSTER_ADDRESS: "gcomm://mariadb_node1,mariadb_node2,mariadb_node3"
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "yes"
    command: 
      - --wsrep-new-cluster
      # - --wsrep_provider=/usr/lib/libgalera_smm.so
      # - --wsrep-on=ON
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data_node1:/var/lib/mysql
      - ./mariadb/migrations:/docker-entrypoint-initdb.d
    networks:
      - galera-net
    restart: unless-stopped

  mariadb_node2:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb_node2
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_GALERA_CLUSTER_NAME: my_galera_cluster
      MARIADB_GALERA_NODE_NAME: node2
      MARIADB_GALERA_NODE_ADDRESS: mariadb_node2
      MARIADB_GALERA_CLUSTER_ADDRESS: "gcomm://mariadb_node1,mariadb_node2,mariadb_node3"
    depends_on:
      - mariadb_node1
    command: 
      # - --wsrep_provider=/usr/lib/libgalera_smm.so
      # - --wsrep-on=ON
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data_node2:/var/lib/mysql
      - ./mariadb/migrations:/docker-entrypoint-initdb.d
    networks:
      - galera-net
    restart: unless-stopped

  mariadb_node3:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb_node3
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_GALERA_CLUSTER_NAME: my_galera_cluster
      MARIADB_GALERA_NODE_NAME: node3
      MARIADB_GALERA_NODE_ADDRESS: mariadb_node3
      MARIADB_GALERA_CLUSTER_ADDRESS: "gcomm://mariadb_node1,mariadb_node2,mariadb_node3"
    depends_on:
      - mariadb_node1
    command: 
      # - --wsrep_provider=/usr/lib/libgalera_smm.so
      # - --wsrep-on=ON
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data_node3:/var/lib/mysql
      - ./mariadb/migrations:/docker-entrypoint-initdb.d
    networks:
      - galera-net
    restart: unless-stopped

  nextjs_app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mariadb_node1
      - mariadb_node2
      - mariadb_node3
    env_file:
      - ./.env.local
    networks:
      - galera-net
    restart: unless-stopped

volumes:
  mariadb_data_node1:
  mariadb_data_node2:
  mariadb_data_node3:


networks:
  galera-net:
    driver: bridge
